"""OWASP ZAP DAST scanner.

Runs ZAP against a live application via the official Docker image, using
the Automation Framework plan generated by ``scanners/zap/automation.py``.

Capabilities:
  • Form / JWT / OAuth2-client-credentials authentication.
  • Spider depth + scope controls (UI-configurable via SpiderConfig).
  • AJAX spider for SPA targets — auto-enabled when the target index
    looks like a JS-bundle landing page.
  • OpenAPI spec auto-discovery on common paths.
  • Session reuse across baseline + active stages so the spider doesn't
    re-discover URLs on combined scans.

The legacy ``scan_target(target_url, scan_type=..., api_spec_path=...)``
signature is preserved for callers that haven't migrated yet.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import httpx

from .zap import (
    AuthConfig,
    OpenApiConfig,
    SpiderConfig,
    ZapScanConfig,
    discover_openapi_spec_url,
)
from .zap.automation import build_automation_plan, render_yaml

logger = logging.getLogger(__name__)

ZAP_IMAGE = "ghcr.io/zaproxy/zaproxy:stable"

# Risk → severity mapping (ZAP riskcode 0..3).
_RISK_TO_SEVERITY = {"3": "high", "2": "medium", "1": "low", "0": "info"}


# --------------------------------------------------------------------------- public class


class ZAPDastScanner:
    """Orchestrates a ZAP DAST scan."""

    def __init__(self, *, image: str = ZAP_IMAGE):
        self.docker_image = image

    # Kept for backward compatibility with existing callers.
    async def scan_target(
        self,
        target_url: str,
        scan_type: str = "baseline",
        api_spec_path: str | None = None,
        auth_config: dict | AuthConfig | None = None,
    ) -> list[dict]:
        config = ZapScanConfig(
            target_url=target_url,
            scan_type=scan_type,
            openapi=OpenApiConfig(spec_path=api_spec_path, auto_discover=api_spec_path is None),
            auth=_coerce_auth(auth_config),
        )
        return await self.scan_with_config(config)

    async def scan_with_config(self, config: ZapScanConfig) -> list[dict]:
        if not await _docker_available():
            logger.warning("Docker not available — ZAP DAST skipped")
            return []
        await _ensure_image(self.docker_image)

        # Auto-detect SPA targets so the AJAX spider kicks in even when
        # the user didn't toggle it explicitly.
        spa_detected = await _looks_like_spa(config.target_url)

        # Auto-discover OpenAPI spec when the user didn't supply one.
        resolved_spec_url: str | None = None
        if (
            config.scan_type in ("api", "combined", "full")
            and config.openapi.auto_discover
            and not config.openapi.spec_path
            and not config.openapi.spec_url
        ):
            resolved_spec_url = await discover_openapi_spec_url(config.target_url)

        with tempfile.TemporaryDirectory() as tmpdir:
            workdir = Path(tmpdir)
            (workdir / "session").mkdir(exist_ok=True)

            # Mount the user's persisted session dir into the container if
            # they specified one. Otherwise we still write into the temp
            # session subdir so jobs share state within this run.
            session_mount = config.session_dir or str(workdir / "session")
            os.makedirs(session_mount, exist_ok=True)

            if config.openapi.spec_path:
                shutil.copy(config.openapi.spec_path, workdir / "openapi-spec")

            plan = build_automation_plan(
                config,
                report_dir="/zap/wrk",
                resolved_openapi_url=resolved_spec_url,
                spa_detected=spa_detected,
            )
            (workdir / "plan.yaml").write_text(render_yaml(plan))
            self._write_auth_scripts(workdir, config.auth)

            cmd = [
                "docker", "run", "--rm",
                "-v", f"{workdir}:/zap/wrk:rw",
                "-v", f"{session_mount}:/zap/wrk/session:rw",
                self.docker_image,
                "zap.sh", "-cmd",
                "-autorun", "/zap/wrk/plan.yaml",
            ]

            try:
                proc = await asyncio.create_subprocess_exec(
                    *cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                try:
                    await asyncio.wait_for(proc.communicate(), timeout=config.timeout_seconds)
                except asyncio.TimeoutError:
                    proc.kill()
                    logger.warning("ZAP scan timed out after %ss", config.timeout_seconds)
                    return []
            except Exception as exc:
                logger.error("ZAP scan invocation failed: %s", exc)
                return []

            return _parse_report(workdir / "zap-report.json")

    # ------------------------------------------------------------------ internals

    @staticmethod
    def _write_auth_scripts(workdir: Path, auth: AuthConfig | None) -> None:
        """Drop the JWT / OAuth helper scripts into the work dir.

        ZAP picks these up because the AF YAML references them by name
        and the Nashorn engine searches ``/zap/wrk/`` first.
        """
        if not auth:
            return
        if auth.jwt:
            (workdir / "fortknoxx-jwt-header.js").write_text(_JWT_SCRIPT)
        if auth.oauth_client_credentials:
            (workdir / "fortknoxx-oauth-cc.js").write_text(_OAUTH_CC_SCRIPT)


# --------------------------------------------------------------------------- helpers


def _coerce_auth(value: dict | AuthConfig | None) -> AuthConfig | None:
    """Accept dicts (from the API layer) or typed configs.

    Schema accepted:
      {"jwt": {"token": "...", "header": "...", "scheme": "Bearer"}}
      {"form": {...}}
      {"oauth_client_credentials": {...}}
    """
    if value is None or isinstance(value, AuthConfig):
        return value
    from .zap.config import (
        FormAuthConfig,
        JwtAuthConfig,
        OAuthClientCredentialsConfig,
    )

    auth = AuthConfig()
    if jwt := value.get("jwt"):
        auth.jwt = JwtAuthConfig(**jwt)
    if form := value.get("form"):
        auth.form = FormAuthConfig(**form)
    if cc := value.get("oauth_client_credentials"):
        auth.oauth_client_credentials = OAuthClientCredentialsConfig(**cc)
    return auth if auth.is_set else None


async def _docker_available() -> bool:
    try:
        proc = await asyncio.create_subprocess_exec(
            "docker", "info",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        await proc.communicate()
        return proc.returncode == 0
    except Exception:
        return False


async def _ensure_image(image: str) -> None:
    try:
        proc = await asyncio.create_subprocess_exec(
            "docker", "image", "inspect", image,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
        )
        await proc.communicate()
        if proc.returncode == 0:
            return
        logger.info("Pulling ZAP image %s", image)
        pull = await asyncio.create_subprocess_exec(
            "docker", "pull", image,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
        )
        await pull.communicate()
    except Exception as exc:
        logger.warning("Failed to ensure ZAP image: %s", exc)


async def _looks_like_spa(target_url: str) -> bool:
    """Heuristic SPA detector — fetch the root and check for a single
    ``<script>`` bundle reference + minimal text content. Cheap enough
    to run on every scan; falls back to False on any error."""
    try:
        async with httpx.AsyncClient(timeout=4.0, follow_redirects=True) as c:
            resp = await c.get(target_url)
    except Exception:
        return False
    if resp.status_code != 200:
        return False
    body = resp.text or ""
    if len(body) > 200_000:
        return False
    has_root_div = 'id="root"' in body or 'id="app"' in body or 'id="__next"' in body
    bundle_ref = ".js" in body and ("/static/" in body or "/_next/" in body or "/assets/" in body)
    return has_root_div and bundle_ref


# --------------------------------------------------------------------------- report parsing


def _parse_report(report_path: Path) -> list[dict]:
    if not report_path.is_file():
        logger.warning("ZAP report not found: %s", report_path)
        return []
    try:
        data = json.loads(report_path.read_text())
    except json.JSONDecodeError as exc:
        logger.error("Bad ZAP report JSON: %s", exc)
        return []

    findings: list[dict] = []
    for site in data.get("site", []):
        for alert in site.get("alerts", []):
            severity = _RISK_TO_SEVERITY.get(str(alert.get("riskcode", "0")), "info")
            cwe = _normalise_cwe(alert.get("cweid"))
            for inst in alert.get("instances", [])[:5]:
                url = inst.get("uri") or inst.get("url") or alert.get("url") or ""
                method = (inst.get("method") or "GET").upper()
                param = inst.get("param") or ""
                findings.append({
                    "title": alert.get("name", "Unknown"),
                    "description": alert.get("desc", ""),
                    "severity": severity,
                    # `file_path` carries the URL path so the triage
                    # fingerprint collapses with Nuclei / Schemathesis
                    # findings on the same endpoint+CWE.
                    "file_path": _url_to_endpoint(url),
                    "url": url,
                    "method": method,
                    "param": param,
                    "line_start": 1,
                    "line_end": 1,
                    "detected_by": "zap_dast",
                    "category": "DAST",
                    "type": alert.get("alert", "web_vulnerability"),
                    "cwe": cwe,
                    "cwe_id": cwe,
                    "owasp_category": _alert_to_owasp(alert),
                    "confidence": alert.get("confidence", "Medium"),
                    "solution": alert.get("solution", ""),
                    "reference": alert.get("reference", ""),
                    "evidence": (inst.get("evidence") or "")[:200],
                })
    logger.info("ZAP DAST produced %d findings", len(findings))
    return findings


def _url_to_endpoint(url: str) -> str:
    """Strip scheme+host so URLs from different scanners normalise."""
    if not url:
        return ""
    parsed = urlparse(url)
    path = parsed.path or "/"
    return path.rstrip("/") or "/"


def _normalise_cwe(value: Any) -> str | None:
    if value in (None, "", "-1", -1):
        return None
    s = str(value).strip()
    return s if s.upper().startswith("CWE-") else f"CWE-{s.lstrip('CWE').lstrip('-')}"


def _alert_to_owasp(alert: dict) -> str:
    name = (alert.get("name") or "").lower()
    table = (
        ("sql", "A03:2021 - Injection"),
        ("xss", "A03:2021 - Injection"),
        ("injection", "A03:2021 - Injection"),
        ("ssrf", "A10:2021 - Server-Side Request Forgery"),
        ("authentication", "A07:2021 - Identification and Authentication Failures"),
        ("session", "A07:2021 - Identification and Authentication Failures"),
        ("access control", "A01:2021 - Broken Access Control"),
        ("authorization", "A01:2021 - Broken Access Control"),
        ("csrf", "A01:2021 - Broken Access Control"),
        ("cryptographic", "A02:2021 - Cryptographic Failures"),
        ("ssl", "A02:2021 - Cryptographic Failures"),
        ("tls", "A02:2021 - Cryptographic Failures"),
        ("logging", "A09:2021 - Security Logging and Monitoring Failures"),
        ("component", "A06:2021 - Vulnerable and Outdated Components"),
    )
    for needle, owasp in table:
        if needle in name:
            return owasp
    return "A05:2021 - Security Misconfiguration"


# --------------------------------------------------------------------------- legacy entry point


async def scan(repo_path: str) -> list[dict]:
    """Static analysis fallback (used when no live target is given)."""
    try:
        from . import zap_scanner as static_zap
        return await static_zap.scan(repo_path)
    except Exception as exc:
        logger.error("Static ZAP scan failed: %s", exc)
        return []


# --------------------------------------------------------------------------- auth scripts (Nashorn)


_JWT_SCRIPT = """\
// fortknoxx-jwt-header.js
// ZAP HTTP Sender script — injects a static bearer token on every
// outbound request. Reads header/value from the active user's
// credentials so multiple users can share one script.
function sendingRequest(msg, initiator, helper) {
    var ext = org.zaproxy.zap.extension.users.ExtensionUserManagement;
    var users = control.getExtensionLoader().getExtension(ext.NAME).getContextUserAuthManager(1);
    if (!users || !users.getUsers() || users.getUsers().size() == 0) return;
    var user = users.getUsers().get(0);
    var creds = user.getAuthenticationCredentials().getCredentials();
    var header = creds["header"] || "Authorization";
    var value = creds["value"] || "";
    if (value !== "") msg.getRequestHeader().setHeader(header, value);
}
function responseReceived(msg, initiator, helper) {}
"""

_OAUTH_CC_SCRIPT = """\
// fortknoxx-oauth-cc.js
// OAuth 2.0 client_credentials grant. Caches the access token and
// refreshes on 401 responses. Lives in the script engine, never on disk.
var cachedToken = null;
function sendingRequest(msg, initiator, helper) {
    if (cachedToken === null) cachedToken = fetchToken(helper);
    if (cachedToken !== null) {
        msg.getRequestHeader().setHeader("Authorization", "Bearer " + cachedToken);
    }
}
function responseReceived(msg, initiator, helper) {
    if (msg.getResponseHeader().getStatusCode() == 401) cachedToken = null;
}
function fetchToken(helper) {
    var ext = org.zaproxy.zap.extension.users.ExtensionUserManagement;
    var users = control.getExtensionLoader().getExtension(ext.NAME).getContextUserAuthManager(1);
    var creds = users.getUsers().get(0).getAuthenticationCredentials().getCredentials();
    var url = new java.net.URL(creds["tokenEndpoint"]);
    var conn = url.openConnection();
    conn.setRequestMethod("POST");
    conn.setDoOutput(true);
    conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
    var body = "grant_type=client_credentials"
        + "&client_id=" + java.net.URLEncoder.encode(creds["clientId"], "UTF-8")
        + "&client_secret=" + java.net.URLEncoder.encode(creds["clientSecret"], "UTF-8");
    if (creds["scope"]) body += "&scope=" + java.net.URLEncoder.encode(creds["scope"], "UTF-8");
    var os = conn.getOutputStream(); os.write(body.getBytes("UTF-8")); os.close();
    var stream = conn.getInputStream();
    var br = new java.io.BufferedReader(new java.io.InputStreamReader(stream));
    var line, sb = new java.lang.StringBuilder();
    while ((line = br.readLine()) !== null) sb.append(line);
    var json = JSON.parse(sb.toString());
    return json.access_token || null;
}
"""
